package com.stockmind.application.factor;
import com.stockmind.application.financial.*;import com.stockmind.application.snapshot.PointInTimeStockSnapshot;import com.stockmind.domain.market.MarketBar;import java.math.*;import java.time.*;import java.util.*;
/** Rebuilds valuation observations using only financial statements published by each trade date. */
public final class HistoricalValuationService{
 /**
  * Reconstructs daily PE/PB observations without look-ahead: each trade date can only see
  * statements whose initial publication and latest update dates were both available then.
  */
 public HistoricalValuationResult calculate(PointInTimeStockSnapshot s){List<Observation>o=new ArrayList<>();for(MarketBar b:s.marketHistory().bars()){LocalDate d=b.closeTime().atZone(ZoneId.of("Asia/Shanghai")).toLocalDate();BigDecimal eps=ttmEps(s,d),bvps=latestMetric(s,"fzb",d,"归属于母公司股东权益每股","每股净资产"),pe=FactorSupport.div(b.close(),eps),pb=FactorSupport.div(b.close(),bvps);if(pe!=null&&pe.signum()<=0)pe=null;if(pb!=null&&pb.signum()<=0)pb=null;if(pe!=null||pb!=null)o.add(new Observation(d,pe,pb));}return new HistoricalValuationResult(List.copyOf(o));}
 private BigDecimal ttmEps(PointInTimeStockSnapshot s,LocalDate d){List<CanonicalFinancialStatementPeriod>p=available(s,"lrb",d);if(p.isEmpty())return null;var latest=p.getFirst();BigDecimal current=FactorSupport.metric(latest,"基本每股收益","每股收益");if(current==null)return null;if(latest.statementScope()==StatementScope.ANNUAL)return current;var priorAnnual=p.stream().filter(x->x.statementScope()==StatementScope.ANNUAL&&x.reportPeriod().isBefore(latest.reportPeriod())).findFirst().orElse(null);var priorSame=p.stream().filter(x->x.statementScope()==latest.statementScope()&&x.reportPeriod().getYear()==latest.reportPeriod().getYear()-1).findFirst().orElse(null);BigDecimal annual=FactorSupport.metric(priorAnnual,"基本每股收益","每股收益"),same=FactorSupport.metric(priorSame,"基本每股收益","每股收益");return annual==null||same==null?null:annual.add(current).subtract(same);}
 private BigDecimal latestMetric(PointInTimeStockSnapshot s,String type,LocalDate d,String...names){return available(s,type,d).stream().map(x->FactorSupport.metric(x,names)).filter(Objects::nonNull).findFirst().orElse(null);}private List<CanonicalFinancialStatementPeriod>available(PointInTimeStockSnapshot s,String type,LocalDate d){return s.financials().statements().getOrDefault(type,List.of()).stream().filter(x->!x.initialPublishedDate().isAfter(d)&&!x.latestUpdatedDate().isAfter(d)).sorted(Comparator.comparing(CanonicalFinancialStatementPeriod::reportPeriod).reversed()).toList();}
 /** Returns the empirical percentile rank in [0, 100], or null for an unusable sample. */
 public BigDecimal percentile(List<BigDecimal>v,BigDecimal target){List<BigDecimal>x=v.stream().filter(Objects::nonNull).sorted().toList();if(target==null||x.isEmpty())return null;long below=x.stream().filter(n->n.compareTo(target)<=0).count();return BigDecimal.valueOf(below*100.0/x.size()).setScale(2,RoundingMode.HALF_UP);}public record Observation(LocalDate date,BigDecimal peTtm,BigDecimal pb){}public record HistoricalValuationResult(List<Observation>observations){public List<BigDecimal>peSince(LocalDate d){return observations.stream().filter(x->!x.date().isBefore(d)).map(Observation::peTtm).filter(Objects::nonNull).toList();}public List<BigDecimal>pbSince(LocalDate d){return observations.stream().filter(x->!x.date().isBefore(d)).map(Observation::pb).filter(Objects::nonNull).toList();}}
}
