package com.stockmind.application.factor;

import com.stockmind.application.financial.CanonicalFinancialStatementPeriod;import com.stockmind.application.snapshot.PointInTimeStockSnapshot;import com.stockmind.domain.factor.*;import java.math.*;import java.util.*;

/** Calculates profitability, cash conversion and balance-sheet quality factors. */
public final class QualityFactorCalculator implements FactorCalculator {
 /** {@inheritDoc} */
 public FactorCategory category(){return FactorCategory.QUALITY;}
 /** Uses same-scope financial periods and leaves unavailable denominators unscored. */
 public FactorCategoryResult calculate(PointInTimeStockSnapshot s){var i=FactorSupport.latest(s,"lrb");var b=FactorSupport.latest(s,"fzb");var c=FactorSupport.latest(s,"llb");List<FactorValue>f=new ArrayList<>();List<FactorWarning>w=new ArrayList<>();List<String>sig=new ArrayList<>();
  BigDecimal rev=FactorSupport.metric(i,"营业总收入","营业收入"),profit=FactorSupport.metric(i,"归属于母公司所有者的净利润","归属于母公司股东的净利润","归属于上市公司股东的净利润","净利润"),ocf=FactorSupport.metric(c,"经营活动产生的现金流量净额"),assets=FactorSupport.metric(b,"资产总计","资产合计"),liab=FactorSupport.metric(b,"负债合计");
  BigDecimal margin=FactorSupport.div(profit,rev),cash=FactorSupport.div(ocf,profit),lev=FactorSupport.div(liab,assets),gap=profit==null?null:FactorSupport.div(profit.subtract(ocf==null?BigDecimal.ZERO:ocf),profit.abs()),ry=FactorSupport.yoy(i,"营业总收入","营业收入"),py=FactorSupport.yoy(i,"归属于母公司所有者的净利润","归属于母公司股东的净利润","归属于上市公司股东的净利润","净利润"),growthGap=py==null||ry==null?null:py.subtract(ry);
  CanonicalFinancialStatementPeriod prev=comparablePrevious(s,i); BigDecimal prevMargin=prev==null?null:FactorSupport.div(FactorSupport.metric(prev,"归属于母公司所有者的净利润","归属于母公司股东的净利润","归属于上市公司股东的净利润","净利润"),FactorSupport.metric(prev,"营业总收入","营业收入"));BigDecimal marginChange=margin==null||prevMargin==null?null:margin.subtract(prevMargin);CanonicalFinancialStatementPeriod prevB=comparablePrevious(s,b,"fzb"),prevC=comparablePrevious(s,c,"llb");BigDecimal prevLev=prevB==null?null:FactorSupport.div(FactorSupport.metric(prevB,"负债合计"),FactorSupport.metric(prevB,"资产总计","资产合计")),prevCash=prev==null||prevC==null?null:FactorSupport.div(FactorSupport.metric(prevC,"经营活动产生的现金流量净额"),FactorSupport.metric(prev,"归属于母公司所有者的净利润","归属于母公司股东的净利润","归属于上市公司股东的净利润","净利润"));
  if(growthGap!=null&&growthGap.compareTo(new BigDecimal("0.30"))>0)w.add(FactorWarning.PROFIT_GROWTH_DIVERGES_FROM_REVENUE);if(cash!=null&&cash.compareTo(new BigDecimal("0.70"))<0)w.add(FactorWarning.CASH_CONVERSION_WEAK);if(cash!=null&&prevCash!=null&&cash.compareTo(new BigDecimal("0.70"))<0&&prevCash.compareTo(new BigDecimal("0.70"))<0)sig.add("连续两个同口径期间现金转化低于0.7");if(marginChange!=null&&marginChange.abs().compareTo(new BigDecimal("0.10"))>0)w.add(FactorWarning.MARGIN_EXPANSION_REQUIRES_EXPLANATION);if(lev!=null&&prevLev!=null&&lev.subtract(prevLev).compareTo(new BigDecimal("0.05"))>0)w.add(FactorWarning.LEVERAGE_RISING);if(i!=null&&prev==null&&s.financials().statements().getOrDefault("lrb",List.of()).size()>1)w.add(FactorWarning.FINANCIAL_SCOPE_NOT_COMPARABLE);
  add(f,"net_margin_pct",margin,"net_profit / revenue",FactorDirection.HIGHER_IS_BETTER,s,i);add(f,"cash_to_net_profit_ratio",cash,"operating_cash_flow / attributable_net_profit",FactorDirection.HIGHER_IS_BETTER,s,i);add(f,"liability_to_asset_pct",lev,"total_liabilities / total_assets",FactorDirection.LOWER_IS_BETTER,s,b);add(f,"cash_flow_gap_pct",gap,"(net_profit-operating_cash_flow)/abs(net_profit)",FactorDirection.LOWER_IS_BETTER,s,i);add(f,"revenue_profit_growth_gap_pct",growthGap,"net_profit_yoy-revenue_yoy",FactorDirection.LOWER_IS_BETTER,s,i);add(f,"margin_change_pct",marginChange,"latest_comparable_margin-prior_comparable_margin",FactorDirection.NEUTRAL,s,i);
  BigDecimal deducted=FactorSupport.metric(i,"扣除非经常性损益后的净利润","扣非净利润"),nonRecurring=profit==null||deducted==null?null:profit.subtract(deducted),nonRecurringRatio=FactorSupport.div(nonRecurring,profit==null?null:profit.abs()),capex=FactorSupport.metric(c,"购建固定资产、无形资产和其他长期资产支付的现金","购建固定资产、无形资产和其他长期资产所支付的现金"),fcf=ocf==null||capex==null?null:ocf.subtract(capex),equity=FactorSupport.metric(b,"归属于母公司股东权益合计","归属于母公司所有者权益合计","所有者权益合计"),prevEquity=FactorSupport.metric(prevB,"归属于母公司股东权益合计","归属于母公司所有者权益合计","所有者权益合计"),avgEquity=equity==null?null:prevEquity==null?equity:equity.add(prevEquity).divide(BigDecimal.TWO,8,RoundingMode.HALF_UP),roe=FactorSupport.div(profit,avgEquity),operatingProfit=FactorSupport.metric(i,"营业利润"),tax=FactorSupport.metric(i,"所得税费用"),totalProfit=FactorSupport.metric(i,"利润总额"),taxRate=FactorSupport.div(tax,totalProfit),nopat=operatingProfit==null?null:operatingProfit.multiply(BigDecimal.ONE.subtract(taxRate==null?new BigDecimal("0.25"):taxRate)),cashBalance=FactorSupport.metric(b,"货币资金"),debt=FactorSupport.metric(b,"短期借款","长期借款"),invested=equity==null||debt==null?null:equity.add(debt).subtract(cashBalance==null?BigDecimal.ZERO:cashBalance),roic=FactorSupport.div(nopat,invested),goodwill=FactorSupport.metric(b,"商誉"),goodwillRatio=FactorSupport.div(goodwill,equity),receivableGap=growthGap(b,i,"应收账款",ry),inventoryGap=growthGap(b,i,"存货",ry);
  add(f,"non_recurring_profit_ratio_pct",nonRecurringRatio,"(net_profit-deducted_net_profit)/abs(net_profit)",FactorDirection.LOWER_IS_BETTER,s,i);addRaw(f,"free_cash_flow_cny",fcf,"operating_cash_flow-capital_expenditure",FactorDirection.HIGHER_IS_BETTER,s,c);add(f,"roe_pct",roe,"net_profit/average_equity",FactorDirection.HIGHER_IS_BETTER,s,i);add(f,"roic_pct",roic,"nopat/(equity+interest_bearing_debt-cash)",FactorDirection.HIGHER_IS_BETTER,s,i);add(f,"receivable_revenue_growth_gap_pct",receivableGap,"receivable_yoy-revenue_yoy",FactorDirection.LOWER_IS_BETTER,s,b);add(f,"inventory_revenue_growth_gap_pct",inventoryGap,"inventory_yoy-revenue_yoy",FactorDirection.LOWER_IS_BETTER,s,b);add(f,"goodwill_to_equity_pct",goodwillRatio,"goodwill/equity",FactorDirection.LOWER_IS_BETTER,s,b);
  if(cash!=null&&cash.compareTo(BigDecimal.ONE)>=0)sig.add("经营现金流覆盖净利润");if(!w.isEmpty())sig.add("盈利质量触发确定性风险检查");return FactorSupport.result(category(),f,w,sig);
 }
 private void add(List<FactorValue>f,String n,BigDecimal v,String formula,FactorDirection d,PointInTimeStockSnapshot s,CanonicalFinancialStatementPeriod p){f.add(v==null?FactorSupport.missing(n,n.endsWith("ratio")?"ratio":"percent",d,s,formula,"财务字段缺失或分母为零"):FactorSupport.value(n,n.endsWith("ratio")?v:FactorSupport.pct(v),v,n.endsWith("ratio")?"ratio":"percent",d,s,p==null?null:p.reportPeriod(),List.of("sina_financial"),formula,FactorQuality.VALID,List.of(),""));}
 private void addRaw(List<FactorValue>f,String n,BigDecimal v,String formula,FactorDirection d,PointInTimeStockSnapshot s,CanonicalFinancialStatementPeriod p){f.add(v==null?FactorSupport.missing(n,"CNY",d,s,formula,"财务字段缺失"):FactorSupport.value(n,v,v,"CNY",d,s,p==null?null:p.reportPeriod(),List.of("sina_financial"),formula,FactorQuality.VALID,List.of(),""));}
 private BigDecimal growthGap(CanonicalFinancialStatementPeriod b,CanonicalFinancialStatementPeriod i,String metric,BigDecimal revenueYoy){BigDecimal y=FactorSupport.yoy(b,metric);return y==null||revenueYoy==null?null:y.subtract(revenueYoy);}
 private CanonicalFinancialStatementPeriod comparablePrevious(PointInTimeStockSnapshot s,CanonicalFinancialStatementPeriod latest){if(latest==null)return null;return s.financials().statements().getOrDefault("lrb",List.of()).stream().skip(1).filter(x->x.statementScope()==latest.statementScope()).findFirst().orElse(null);}
 private CanonicalFinancialStatementPeriod comparablePrevious(PointInTimeStockSnapshot s,CanonicalFinancialStatementPeriod latest,String type){if(latest==null)return null;return s.financials().statements().getOrDefault(type,List.of()).stream().skip(1).filter(x->x.statementScope()==latest.statementScope()).findFirst().orElse(null);}
}
