package com.stockmind.application.factor;
import com.stockmind.application.snapshot.PointInTimeStockSnapshot;import com.stockmind.domain.factor.*;import java.math.*;import java.time.*;import java.util.*;import java.util.stream.*;
/** Calculates trailing cash-return and dividend-continuity factors. */
public final class ShareholderReturnFactorCalculator implements FactorCalculator{
 /** {@inheritDoc} */
 public FactorCategory category(){return FactorCategory.SHAREHOLDER_RETURN;}
 /** Uses ex-dividend dates available by the snapshot date and does not infer payout coverage. */
 public FactorCategoryResult calculate(PointInTimeStockSnapshot s){Map<Integer,BigDecimal>annual=s.dividends().stream().collect(Collectors.groupingBy(x->x.exDividendDate().getYear(),TreeMap::new,Collectors.mapping(x->x.cashPerTenShares().divide(BigDecimal.TEN,8,RoundingMode.HALF_UP),Collectors.reducing(BigDecimal.ZERO,BigDecimal::add))));BigDecimal ttm=s.dividends().stream().filter(x->!x.exDividendDate().isBefore(s.requestedAsOf().minusYears(1))).map(x->x.cashPerTenShares().divide(BigDecimal.TEN,8,RoundingMode.HALF_UP)).reduce(BigDecimal.ZERO,BigDecimal::add),yield=FactorSupport.div(ttm,s.marketPrice().priceCny());List<BigDecimal>last3=annual.entrySet().stream().sorted(Map.Entry.<Integer,BigDecimal>comparingByKey().reversed()).limit(3).map(Map.Entry::getValue).toList();BigDecimal cagr=null;if(last3.size()==3&&last3.get(2).signum()>0)cagr=BigDecimal.valueOf(Math.pow(last3.get(0).divide(last3.get(2),12,RoundingMode.HALF_UP).doubleValue(),0.5)-1);int continuous=0;for(int y=s.requestedAsOf().getYear();annual.getOrDefault(y,BigDecimal.ZERO).signum()==0&&y>=s.requestedAsOf().getYear()-1;y--){if(y<s.requestedAsOf().getYear()-1)break;}for(int y=s.requestedAsOf().getYear()-1;annual.getOrDefault(y,BigDecimal.ZERO).signum()>0;y--)continuous++;BigDecimal stability=stability(last3);List<FactorValue>f=new ArrayList<>();add(f,"ttm_cash_dividend_per_share",ttm,"CNY_per_share",FactorDirection.HIGHER_IS_BETTER,s,"sum(last12m cash_per_ten_shares/10)");add(f,"ttm_dividend_yield_pct",yield,"percent",FactorDirection.HIGHER_IS_BETTER,s,"ttm_dividend_per_share/snapshot_price");add(f,"dividend_3y_cagr_pct",cagr,"percent",FactorDirection.HIGHER_IS_BETTER,s,"(latest_annual_dividend/third_year_dividend)^(1/2)-1");add(f,"continuous_dividend_years",BigDecimal.valueOf(continuous),"years",FactorDirection.HIGHER_IS_BETTER,s,"continuous completed calendar years with cash dividend");add(f,"dividend_stability",stability,"ratio",FactorDirection.HIGHER_IS_BETTER,s,"1-coefficient_of_variation(last3 annual dividends)");f.add(FactorSupport.missing("dividend_coverage_status","enum",FactorDirection.NEUTRAL,s,"dividend / distributable_profit_or_eps","快照缺少可靠TTM每股收益口径"));return FactorSupport.result(category(),f,List.of(),List.of("annual_dividend_per_share="+annual));}
 private BigDecimal stability(List<BigDecimal>v){if(v.size()<2)return null;double m=v.stream().mapToDouble(BigDecimal::doubleValue).average().orElse(0);if(m==0)return null;double sd=Math.sqrt(v.stream().mapToDouble(x->Math.pow(x.doubleValue()-m,2)).sum()/v.size());return BigDecimal.valueOf(Math.max(0,1-sd/m));}private void add(List<FactorValue>f,String n,BigDecimal v,String unit,FactorDirection d,PointInTimeStockSnapshot s,String formula){f.add(FactorSupport.value(n,"percent".equals(unit)?FactorSupport.pct(v):v,v,unit,d,s,s.marketPrice().effectiveTradeDate(),List.of("eastmoney_dividend"),formula,v==null?FactorQuality.MISSING:FactorQuality.VALID,List.of(),v==null?"数据不足":""));}
}
