package com.stockmind.domain.factor;

public enum FactorWarning {
    PROFIT_GROWTH_DIVERGES_FROM_REVENUE,
    CASH_CONVERSION_WEAK,
    MARGIN_EXPANSION_REQUIRES_EXPLANATION,
    LEVERAGE_RISING,
    FINANCIAL_SCOPE_NOT_COMPARABLE,
    LOW_PE_REQUIRES_CONTEXT,
    LOW_FORECAST_SAMPLE,
    NEGATIVE_EARNINGS,
    CURRENT_ONLY_PEER_DATA,
    UPCOMING_LOCKUP_RELEASE,
    MARGIN_CROWDING_RISING,
    SHAREHOLDER_DISPERSION_RISING,
    BLOCK_TRADE_DISCOUNT,
    INSUFFICIENT_DATA
}
